import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import Link from "next/link";

import Nav from "@/components/navigation/nav";
import { cn } from "@/lib/utils";

const inter = Nunito_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  profile,
}: Readonly<{
  children: React.ReactNode;
  profile: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn( "px-6 md:px-12 max-w-7xl mx-auto",`${inter.className}`)}>
        <Nav></Nav>
         {children}
        </body>
    </html>
  );
}
