import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

import Nav from "@/components/navigation/nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  profile,
}: Readonly<{
  children: React.ReactNode;
  profile: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <nav className="flex gap-2 justify-between px-4 bg-blue-700 ">
          <ul>
            <li><Link href="/">Home</Link></li>
          </ul>
        </nav>
            <Nav/>
            {children}
        </body>
    </html>
  );
}
